# -*- coding: utf-8 -*-
"""PRO-C111-Project-Boilerplate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o5n8tK1rfakLDD35MFAgfRkcASzUoxKN

Clone the required dataset from given
"""

#Cloning the required dataset
!git clone https://github.com/procodingclass/Pro-M3-Hurricane-Damage-Dataset

"""Display first image from training dataset"""

#Display image
from matplotlib import pyplot
from matplotlib.image import imread

training_damaged_image = "/content/Pro-M3-Hurricane-Damage-Dataset/train/damage/image (1).jpeg"

# load image pixels
image = imread(training_damaged_image)

pyplot.title("damaged: Image 1")

# plot raw pixel data
pyplot.imshow(image)

# show the figure
pyplot.show()

"""Perform augmentation on Training dataset"""

#zoom and horizontal flip (Or any augmentation technique of your choice)

"""Visualize the augmented images in four sub-plots"""

#Visualize the preprocessed image